### ISSUE TITLE
Вопрос по Лаб0

### ISSUE THREAD

**Issue by gmalik1998** [agsh/fp18#1]
Здравствуйте, не проходит тест на F#. Ответ, вроде, правильный

**Comment by agsh** [comment]
Да, уже заметил, завтра вечером разберусь. Раньше не получится :(

**Comment by agsh** [comment]
Вроде бы исправил. Можно проверить только на одногруппниках. Как у них?

**Comment by gmalik1998** [comment]
У одногруппников, если смотреть по результатом, задача зашла. У меня не заходит:( Ошибка у меня? Я вроде протестил

**Comment by gmalik1998** [comment]
Вы исправили?

**Comment by agsh** [comment]
Да, и даже протестировал)
