### ISSUE TITLE
lab 1 Метод итерации

### ISSUE THREAD

**Issue by alloky** [agsh/fp18#2]
Имеется в виду `x_{n+1} = f(x_n)` или что? Если так, то что делать эли эта последовательность расходится?

**Comment by AShedko** [comment]
Я писал метод простой итерации (Ньютон, где вместо производной её первое приближение [первая разность])

**Comment by alloky** [comment]
я в качестве производной в Ньютоне брал  (f (x + delta ) - f x)/delta, чтобы для произвольной функции работало

**Comment by agsh** [comment]
Обсудили на семинаре
